name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name == 'main' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: sudo apt -qq install libgtk-3-dev
        if: runner.os == 'Linux'
      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
      - run: make
        if: runner.os != 'Windows'
      - run: nmake
        if: runner.os == 'Windows'
      - name: Build examples
        run: odin build examples/main.odin -file
